### ISSUE TITLE
installation issue with cose or gamma

### ISSUE THREAD

**Issue by jimmy-adams** [ucb-bar/dosa#2]
Hello,

I try to use the dosa to evaluate the simba-like arch. But I ran into problems when using git. Hope you can help me with it.
When git clone with the ssh mode, I found there are several empty repos waiting for further installation or git clone, including the accelergy-timeloop-infra, both the cosa and gamma-timeloop under the mapper repos.
That adds much more efforts to make the dosa work. Can you suggest a more efficient way to complete the installation?

**Comment by charleshong3** [comment]
Hi, to clone these git [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) you can run `git submodule update --init --recursive`. You then have to install Timeloop and Accelergy separately, you can do so according to the [documentation](https://timeloop.csail.mit.edu/). You will also need a Gurobi optimizer license if you want to use CoSA (academic licenses are free).

Just a note, we are currently focused on modeling Gemmini so I haven't checked the Simba flow in a while (it may be out of date). Feel free to post back here if you find any issues with it.
